theme: jekyll-theme-minimal

# Name
name: Akshay Chandrashekaran

# Description
description: My Personal Blog

#URL for avatar
avatar: https://avatars3.githubusercontent.com/u/702424?v=3&s=460

footer-links:
  github: akshayc11
  linkedin: https://www.linkedin.com/in/akshay-chandrashekaran-6687a31b/
  email: blog@akshayc.com
  

url: http://akshayc.com

permalink: /:title/
# Jekyll version
version v1.2.0
# Kramdown for markdown
kramdown:
  # Github flavored markdown
  input: GFM
  # Syntax highlighting
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # use pygments syntax highlighting css
    css_class: 'highlight'

# Sass partial directory
sass:
  style: :expanded

# Other plugins
gems:
   - jekyll-sitemap # Create Jekyll sitemap using gem
   - jekyll-feed # Create  an Atom feed

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - CNAME